# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  database: first_app_development
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  <<: *default
  adapter: mysql2
  database: first_app_test
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>